name: Docker
on:
  push:
    branches:
      - master
    paths-ignore:
     - 'mod/**'
     - 'patches/**'
     - 'README.md'
     - '.github/**'
     - 'architecture.md'
     - 'CHANGELOG.md'
     - 'CONTRIBUTING.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images using cache
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: bttv-android
          password: "${{ secrets.BGITHUB_TOKEN }}"
          registry: ghcr.io
          image_name: builder
